// TMC内容管理api
export default {
  API_LIST_CONTENT: {
    // ------手记----
    // 获取康复案例
    INTERFACE_GET_INQUIRYCASE_LISTBYCONDITION: "api/tmc/inquiryCase/listByCondition",
    // 添加康复案例
    INTERFACE_GET_INQUIRYCASE_ADD: "api/tmc/inquiryCase/add",
    // 删除康复案例
    INTERFACE_GET_INQUIRYCASE_DELETE: "api/tmc/inquiryCase/delete",
    // 发布康复案例
    INTERFACE_GET_INQUIRYCASE_ISPUBLISH: "api/tmc/inquiryCase/isPublish",
    // 获取单个康复案例
    INTERFACE_GET_INQUIRYCASE_DETAIL: "api/tmc/inquiryCase/detail",
    // 修改康复案例
    INTERFACE_GET_INQUIRYCASE_UPDATE: "api/tmc/inquiryCase/update",
    // ---------展示医生-----------
    // 获取医院下所有医生
    INTERFACE_GET_HOSPITALSTAFF_GETSTAFFLISTBYORGID: "api/peachUser/hospitalStaff/getStaffListByOrgID",
    // 获取展示医生列表数据
    INTERFACE_GET_DOCTORSHOW_LIST: "api/tmc/doctorShow/list",
    // 添加医生展示列表
    INTERFACE_POST_DOCTORSHOW_ADD: "api/tmc/doctorShow/add",
    // 删除医生展示
    INTERFACE_POST_DOCTORSHOW_DELETE: "api/tmc/doctorShow/delete",
    // 修改医生展示排序
    INTERFACE_POST_DOCTORSHOW_UPDATE: "api/tmc/doctorShow/update",
    // --------文章---------
    // 文章编辑与添加
    INTERFACE_POST_ARTICLE_SAVE: "/api/tmc/article/save",
    // 获取文章列表
    INTERFACE_GET_ARTICLE_LIST: "/api/tmc/article/list",
    // 文章删除
    INTERFACE_GET_ARTICLE_DELETE: "/api/tmc/article/delete",
    // 文章置顶
    INTERFACE_GET_ARTICLE_UPDATETOP: "/api/tmc/article/updateTop",
    // 获取文章详情
    INTERFACE_GET_ARTICLE_GETARTICLEBYKEYID: "/api/tmc/article/getArticleByKeyID",
    // 发布文章
    INTERFACE_GET_ARTICLE_PUBLISHARTICLEOPTION: "/api/tmc/article/publishArticleOption",
    // --------患者分享------------
    // 添加患者分享
    INTERFACE_GET_PATIENTSHARE_ADD: "api/tmc/patientShare/add",
    // 获取患者分享列表
    INTERFACE_GET_PATIENTSHARE_LISTBYCONDITION: "api/tmc/patientShare/listByCondition",
    // 置顶患者分享
    INTERFACE_GET_PATIENTSHARE_ISTOP: "api/tmc/patientShare/isTop",
    // 发布患者分享
    INTERFACE_GET_PATIENTSHARE_ISPUBLISH: "api/tmc/patientShare/isPublish",
    // 获取患者分享
    INTERFACE_GET_PATIENTSHARE_DETAIL: "api/tmc/patientShare/detail",
    // 删除患者分享
    INTERFACE_GET_PATIENTSHARE_DELETE: "api/tmc/patientShare/delete",
    // 修改患者分享
    INTERFACE_GET_PATIENTSHARE_UPDATE: "api/tmc/patientShare/update",
    // ------------内容审核--------------------
    // 查询文章评论列表
    INTERFACE_GET_ARTICLECOMMENAT_LIST: "api/comment/comment/list",
    // 文章已读/未读
    INTERFACE_POST_ARTICLECOMMENAT_READ: "api/comment/comment/read",
    // 文章展示/不展示
    INTERFACE_POST_ARTICLECOMMENAT_UPDATESHOW: "api/comment/comment/updateShow",
    // 文章置顶/不置顶
    INTERFACE_POST_ARTICLECOMMENAT_UPDATETOP: "api/comment/comment/updateTop",
    // 文章评论删除
    INTERFACE_POST_ARTICLECOMMENAT_DEL: "api/comment/comment/del",
    // 文章标题列表
    INTERFACE_GET_ARTICLE_TITLELIST: "api/tmc/article/titleList",
    // 文章回复评论
    INTERFACE_POST_ARTICLECOMMENAT_REPLY: "api/comment/comment/reply",
    // 根据ID查询评论的对象
    INTERFACE_GET_ARTICLETITLE_BY_KEYID: "api/comment/comment/getObjectTitles"
  }
};
