// 风湿病相关api
export default {
  API_LIST_HOUSHI: {
    // 修改就诊患者信息 + 修改患者信息
    API_HOU_PATIENT_UPDATAPATIENTINFO: "api/hou/patient/updataPatientInfo",
    // 获取风湿药品列表
    API_HOU_MEDICINE_LIST: "api/hou/medicine/list",
    // 修改药品价格和服务费
    API_HOU_MEDICINE_MODIFY: "api/hou/medicine/modify",
    // 获取财务订单列表
    API_HOU_ORDERSFINANCE_LIST: "api/hou/order/financingList",
    // 药品发货订单列表
    API_HOU_MEDICINEDELIVERY_LIST: "api/hou/order/deliveryList",
    // 处方审核单列表
    API_HOU_RPORDERS_LIST: "api/hou/order/rpList",
    // // 查询用户信息
    // API_HOU_PATIENT_PATIENTINFO: "/hou/patient/getPatient",
    // 获取订单处方
    API_HOU_ORDER_READRP: "api/hou/order/readRp",
    // 获取订单详情
    API_HOU_ORDER_READ: "api/hou/order/read",
    // 药师审核处方
    API_HOU_ORDER_AUDIT: "api/hou/order/audit",
    // 获取订单辨病
    API_HOU_ORDER_READDISEASE: "api/hou/order/readDisease",
    // 患者信息
    // 获取订单患者信息
    API_HOU_ORDER_PATIENTINFO: "api/hou/order/readPatientInfo",
    // 获取患者病史版本详情
    API_HOU_PATIENT_READPATIENTHISTORY: "api/hou/patient/readPatientHistory",
    // 风湿财务订单发起结算时读取药品分润详情
    API_HOU_ORDER_ORDERMEDICINEPROFIT: "api/hou/order/orderMedicineProfit",
    // 发起结算
    API_HOU_ORDER_BEGINPROFIT: "api/hou/order/beginProfit",
    // 医院端患者列表
    API_HOU_PATIENT_HOUPATIENTLIST: "api/hou/patient/houPatientList",
    // 根据病种编号查询病情基础数据
    API_HOU_BASIC_GETCONDITION: "api/hou/basic/getCondition",
    // 医院端患者列表
    API_HOU_PATIENT_GETSCORECOMPARISON: "api/hou/patient/getScoreComparison",
    // 获取协诊列表
    API_HOU_COTREAT_LIST: "api/hou/coTreat/list",
    // 辨病论症
    // 第一步，新建订单，写入患者信息
    API_HOU_TREAT_CREATEORDER: "api/hou/treat/createOrder",
    // 第二部获取所有的病种
    API_HOU_BASIC_GETDISEASE: "api/hou/basic/getDisease",
    // 查询病史分类
    API_HOU_HISTORY_CLASSIFY: "api/hou/basic/getHistoryClass",
    // 通过病史分类获得分组
    API_HOU_BASIC_GETHISTORYGROUP: "api/hou/basic/getHistoryGroup",
    // 获取病史版本最新数据
    API_HOU_PATIENT_GETSHOWHISTORY: "/api/hou/patient/getShowHistory",
    // 获取分组项目基础数据
    API_HOU_BASIC_GETHISTORYITEM: "/api/hou/basic/getHistoryItem",
    // 添加病史组使用
    API_HOU_TREAT_ADDHISTORYITEMS: "/api/hou/treat/addHistoryItems",
    // 确认发货
    API_HOU_ORDER_DELIVERY: "/api/hou/order/delivery",
    // 根据分组Code获取文本数据
    API_HOU_PATIENT_GETHISTORYGROUPBYGROUPCODE: "/api/hou/patient/getHistoryGroupByGroupCode",
    // 根据分组Code 获取选择数据
    API_HOU_PATIENT_GETHISTORYBYGROUPCODE: "/api/hou/patient/getHistoryByGroupCode",
    // 获取患者评分总表数据
    API_HOU_PATIENT_GETALLSCORE: "api/hou/patient/getAllScore",
    // 修改病史组使用
    API_HOU_TREAT_UPDATEHISTORYGROUPS: "/api/hou/treat/updateHistoryGroups",
    // 获取辩病论治数据
    API_HOU_ARGUE_DISEASETREATMENT: "/api/hou/basic/getSymptomQaItem",
    // 读取病症选中数据
    API_HOU_ORDER_READSYMPTOM: "/api/hou/order/readSymptom",
    // 保存辩证结果项
    API_HOU_TREAT_ADDSYMPTOM: "/api/hou/treat/addSymptom",
    // 根据病种Code 病症Code 获取基础数据
    API_HOU_BASIC_GETKINDNAMEBYDISCODE: "api/hou/basic/getKindNameByDisCode",
    // 获取模板开方数据
    API_HOU_TEMPLATES_EVOLUTIONS: "/api/hou/medicine/getMedicineByDiseaseCode",
    // 修改医院端提交的病种
    API_HOU_TREAT_MODIFYORDERDISEASE: "/api/hou/treat/modifyOrderDisease",
    // 通过病证编号获取药品
    API_HOU_MEDICINE_GETSYMPTOMMEDICINE: "api/hou/medicine/getSymptomMedicine",
    // 获取风险类型
    API_HOU_PATIENT_GETPATIENTAGE: "/api/hou/patient/getPatientAge",
    // 添加处方
    API_HOU_TREAT_ADDRP: "/api/hou/treat/addRp",
    // 获取患者评分基础数据
    API_HOU_PATIENT_PATIENTCONDITIONLIST: "/api/hou/patient/patientConditionList",
    // 获取患者评分数据
    API_HOU_PATIENT_PATIENTCONDITION: "/api/hou/patient/patientCondition",
    // rp服务
    // 获取userSig
    API_RP_INITIAL_GETUSERSIG: "api/rp/initial/getUserSig",
    // 获取视频房间号
    API_RP_INITIAL_GETROOMID: "api/rp/initial/getRoomId",
    // 修改问诊状态
    API_RP_INQUIRY_UPDATEINQUIRYTYPE: "api/rp/inquiry/updateInquiryType",
    // 结束问诊
    API_RP_INQUIRY_END: "api/rp/inquiry/end",
    // 设置医生在线状态
    API_RP_IMSTATUS_SETFREE: "api/rp/imStatus/setFree"
  }
};
